services:
  www:
    container_name: www
    build: .
    restart: unless-stopped
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/mattmccarthy.io.conf:/etc/nginx/conf.d/mattmccarthy.io.conf:ro
      - ./nginx/conf.d/mattmccarthy.net.conf:/etc/nginx/conf.d/mattmccarthy.net.conf:ro
      - ./nginx/conf.d/mattmccarthy.org.conf:/etc/nginx/conf.d/mattmccarthy.org.conf:ro
      - ./nginx/conf.d/mccarthycode.com.conf:/etc/nginx/conf.d/mccarthycode.com.conf:ro
      - ./nginx/conf.d/redirect-http-to-https.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl/mattmccarthy.io.crt:/etc/ssl/certs/mattmccarthy.io.crt:ro
      - ./nginx/ssl/mattmccarthy.io.key:/etc/ssl/private/mattmccarthy.io.key:ro
      - ./nginx/ssl/mattmccarthy.net.crt:/etc/ssl/certs/mattmccarthy.net.crt:ro
      - ./nginx/ssl/mattmccarthy.net.key:/etc/ssl/private/mattmccarthy.net.key:ro
      - ./nginx/ssl/mattmccarthy.org.crt:/etc/ssl/certs/mattmccarthy.org.crt:ro
      - ./nginx/ssl/mattmccarthy.org.key:/etc/ssl/private/mattmccarthy.org.key:ro
      - ./nginx/ssl/mccarthycode.com.crt:/etc/ssl/certs/mccarthycode.com.crt:ro
      - ./nginx/ssl/mccarthycode.com.key:/etc/ssl/private/mccarthycode.com.key:ro
