server {
    listen 443 ssl;
    server_name mattmccarthy.net www.mattmccarthy.net;

    ssl_certificate     /etc/ssl/certs/mattmccarthy.net.crt;
    ssl_certificate_key /etc/ssl/private/mattmccarthy.net.key;

    return 301 https://mattmccarthy.io;
}
