server {
    listen 443 ssl;
    server_name mattmccarthy.org www.mattmccarthy.org;

    ssl_certificate     /etc/ssl/certs/mattmccarthy.org.crt;
    ssl_certificate_key /etc/ssl/private/mattmccarthy.org.key;

    return 301 https://mattmccarthy.io;
}
