server {
    listen 443 ssl;
    server_name mattmccarthy.local *.mattmccarthy.local;

    ssl_certificate     /etc/ssl/certs/mattmccarthy.local.crt;
    ssl_certificate_key /etc/ssl/private/mattmccarthy.local.key;

    location / {
        proxy_pass http://www:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Prefix /;
    }
}
