server {
    listen 443 ssl;
    server_name mccarthycode.com www.mccarthycode.com;

    ssl_certificate     /etc/ssl/certs/mccarthycode.com.crt;
    ssl_certificate_key /etc/ssl/private/mccarthycode.com.key;

    return 301 https://mattmccarthy.io;
}
